### ISSUE TITLE
'raw_data/baxter.braycurtis.pcoa.axes' does not exist

### ISSUE THREAD

**Issue by klausbh** [pschloss/minimalR#10]
Hello,

I just revisited minimalR to prepare for a class I am co-teaching on Friday, and was surprised to find that the script for "session 2: scatter plots" failed on the third line of code:

pcoa <- read_tsv(file="raw_data/baxter.braycurtis.pcoa.axes")
Error: 'raw_data/baxter.braycurtis.pcoa.axes' does not exist in current working directory ('/cloud/project').

This file was, in fact, missing from "raw_data-0.1.zip" but substituting  "baxter.thetayc.pcoa.axes" worked fine.

Thanks for the excellent tutorials!

Sincerely,
-Klaus

**Comment by pschloss** [comment]
Thanks for your interest in using these materials with your class! Can you tell me where you got a link to version 0.1 of `raw_data`? There should be a link to the [latest version](https://github.com/riffomonas/raw_data/releases/latest), which is 0.3 and that has `baxter.braycurtis.pcoa.axes`.

Pat

**Comment by klausbh** [comment]
Hi Pat,

Thanks for your quick response! At "https://riffomonas.org/minimalR/00_installation.html" under "What you need to do these tutorials…" the 3rd bullet point "Raw data files" links to "https://github.com/riffomonas/raw_data/archive/0.1.zip". Using the newer version is an even easier fix than I had anticipated.

Cheers,
-Klaus

**Comment by pschloss** [comment]
Thanks! I’ll update the link ;)

Pat

**Comment by klausbh** [comment]
Great - I'll go ahead and close the issue, then.

Thanks again,
-Klaus
