### ISSUE TITLE
Session 1: Activity 2 - Add hint to tell how to find what packages are loaded

### ISSUE THREAD

**Issue by NLesniak** [pschloss/minimalR#4]
It would be helpful to include a hint with what function should be run to see what packages are loaded, possibly with `(.packages())`

**Comment by pschloss** [comment]
Hmmm. From the terminal, when I do

```r
library(tidyverse)
```

I get...

```r
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 2.2.1.9000     ✔ purrr   0.2.4     
✔ tibble  1.4.2          ✔ dplyr   0.7.4     
✔ tidyr   0.8.0          ✔ stringr 1.3.0     
✔ readr   1.1.1          ✔ forcats 0.2.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
```

I see that inside RStudio I don't get this output. Not sure what's happening.

**Comment by pschloss** [comment]
I can't seem to get `.packages()` to work - what would be the syntax for checking what is loaded with `tidyverse`?

**Comment by NLesniak** [comment]
you're missing the encasing parentheses `(.packages())`

**Comment by NLesniak** [comment]
`(.packages())` will show all the packages currently loaded into the library, you could also try `tidyverse_packages()` which will give you all the packages in tidyverse (but not necessarily loaded)
