### ISSUE TITLE
Orphan paragraph in 01_scatter_plots.Rmd

### ISSUE THREAD

**Issue by cramjaco** [pschloss/minimalR#9]
There seems to be a paragraph that does not correspond to the code on line 200 of lesson 01 (01_scatter_plots.Rmd). It discusses variables "p", "a" and "b". This may correspond to code that was later simplified out of the lesson. This paragraph could be removed, relocated elsewhere, or the code changed to reflect the content of the paragraph. I wasn't sure which the authors would prefer, so I am posting this as an issue rather than a pull request.

Thanks for this great tutorial and considering the modification.

**Comment by pschloss** [comment]
Thanks, @cramjaco for catching that. You're right that this is a vestige of old text that showed how to build up a ggplot with addition to a variable and introduced the assignment operator.
